apiVersion: v1
kind: ServiceAccount
metadata:
  name: topic-access
---
apiVersion: gcp-kafka.k8s.onpier.de/v1alpha1
kind: KafkaUser
metadata:
  name: topic-access
spec:
  serviceAccountName: topic-access
  topicAccess:
    - topic: test-auto-create
      role: readWrite
