apiVersion: v1
kind: ServiceAccount
metadata:
  name: topic-access
---
apiVersion: gcp-kafka.k8s.onpier.de/v1alpha1
kind: User
metadata:
  name: topic-access
spec:
  serviceAccountName: topic-access
  topicAccess:
    - topic: t1
      role: readWrite
