apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kafka-access-test
  name: topic-access
spec:
  serviceAccountName: topic-access
  containers:
  - name: kafka-client
    image: ghcr.io/onpier-oss/gcp-kafka-test-topic-access
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    env:
      - name: GCP_PROJECT
        value: < GCP PROJECT ID >
      - name: GCP_REGION
        value: < REGION >
      - name: KAFKA_CLUSTER_NAME
        value: < AN ID OF THE KAFKA CLUSTER > 
      - name: KAFKA_TOPIC
        value: < A TOPIC TO TEST AGAINST > 
  - name: auth-proxy
    image: ghcr.io/onpier-oss/gcp-kafka-proxy
    imagePullPolicy: Always
    ports:
      - containerPort: 14293
