apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kafka-access-test
  name: topic-access
spec:
  serviceAccountName: topic-access
  containers:
  - name: kafka-client
    image: europe-west3-docker.pkg.dev/ic-gmb-d-workload/gcr/test-kafka-topic-access
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    env:
      - name: GCP_PROJECT
        value: ic-gmb-d-workload
      - name: GCP_REGION
        value: europe-west3
      - name: KAFKA_CLUSTER_NAME
        value: gmb-d-euw3
      - name: KAFKA_TOPIC
        value: t1
  - name: auth-proxy
    image: europe-west3-docker.pkg.dev/ic-gmb-d-workload/gcr/kafka-gcp-credentials-server
    imagePullPolicy: Always
    ports:
      - containerPort: 14293
