FROM golang:latest as builder
WORKDIR /workdir
COPY . .
RUN go build -o test

FROM ubuntu
WORKDIR /root
RUN apt-get update -y && apt-get install -y ca-certificates default-jre wget unzip
RUN wget -O kafka_2.13-3.7.2.tgz  https://downloads.apache.org/kafka/3.7.2/kafka_2.13-3.7.2.tgz
RUN tar xfz kafka_2.13-3.7.2.tgz
RUN mv kafka_2.13-3.7.2 kafka
ENV KAFKA_HOME=/root/kafka
ENV PATH=$PATH:$KAFKA_HOME/bin
RUN wget https://github.com/googleapis/managedkafka/releases/download/v1.0.5/release-and-dependencies.zip
RUN unzip -n release-and-dependencies.zip -d $KAFKA_HOME/libs/
RUN mv $KAFKA_HOME/libs/release-and-dependencies/dependency/* $KAFKA_HOME/libs/
RUN mv $KAFKA_HOME/libs/release-and-dependencies/managed-kafka-auth-login-handler-1.0.5.jar $KAFKA_HOME/libs/
RUN rm -rf $KAFKA_HOME/libs/release-and-dependencies
COPY client.properties .
COPY --from=builder /workdir/test /test
CMD ["/test"]
