apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: gcp-kafka-auth-operator
    app.kubernetes.io/managed-by: kustomize
  name: kafka-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: gcp-kafka-auth-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
      containers:
      - command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
          - --gcp-project-id=< GCP PROJECT ID > 
          - --region=< REGION >
          - --kafka-cluster=< KAFKA CLUSTER ID >
          - --admin-user-email=< OPERATOR SA EMAIL >
        image: controller
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      - name: auth-proxy
        image: ghcr.io/onpier-oss/gcp-kafka-auth-proxy
        imagePullPolicy: Always
        ports:
          - containerPort: 14293
      serviceAccountName: kafka-operator
      terminationGracePeriodSeconds: 10
