FROM golang:latest as builder
WORKDIR /workdir
COPY . .
RUN go build -o checker

FROM ubuntu
RUN apt-get update -y && apt-get install -y ca-certificates default-jre wget unzip
COPY --from=builder /workdir/checker /checker
CMD ["/checker"]
