apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: gcp-kafka-auth-operator
    app.kubernetes.io/managed-by: kustomize
  annotations:
    iam.gke.io/gcp-service-account: kafka-operator@ic-gmb-d-workload.iam.gserviceaccount.com
  name: kafka-operator
  namespace: system
