---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-test-auth
spec:
  serviceAccountName: kafka-test-auth
  containers:
  - name: kafka-test-auth
    image: ghcr.io/onpier-oss/gcp-kafka-operator-test-auth
    ports:
    - containerPort: 80
    env:
      - name: GCP_PROJECT
        value: < THE PROJECT NAME>
      - name: GCP_REGION
        value: < REGION > 
      - name: GCP_CLUSTER_ID
        value: < ID OF THE KAFKA CLUSTER >
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-test-auth
---
apiVersion: gcp-kafka.k8s.onpier.de/v1alpha1
kind: User
metadata:
  name: user-1
spec:
  serviceAccountName: kafka-test-auth
  topicAccess:
    - topic: < TOPIC NAME >
      role: readOnly
