
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gcp-kafka-operator.fullname" . }}
  labels:
    {{- include "gcp-kafka-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gcp-kafka-operator.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "gcp-kafka-operator.labels" . | nindent 8 }}
    spec:
      securityContext:
      containers:
      - command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
          - --gcp-project-id={{ .Values.config.gcpProject }}
          - --region={{ .Values.config.region }}
          - --kafka-cluster={{ .Values.config.kafkaCluster }}
          - --admin-user-email={{ .Values.config.adminSAEmail }}
        image: {{ include "gcp-kafka-operator.imageBootsrap" .Values.images.controller }}
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      - name: auth-proxy
        image: {{ include "gcp-kafka-operator.imageBootsrap" .Values.images.proxy }}
        imagePullPolicy: Always
        ports:
          - containerPort: 14293
      serviceAccountName: {{ include "gcp-kafka-operator.fullname" . }}
      terminationGracePeriodSeconds: 10
