{{- $manifests := dict }}
{{- range $path, $index :=  .Files.Glob  "crds/*" }}
  {{- $file := $.Files.Get $path }}
  {{- $_ := set $manifests ($index | toString ) $file }}
{{- end }}
{{- range $_, $file := $manifests }}
---
{{- $manifest := $file | fromYaml }}
apiVersion: {{ get $manifest "apiVersion" }}
kind: {{ get $manifest "kind" }}
{{- $metadata := get $manifest "metadata" }}
metadata:
  name: {{ get $metadata "name" }}
  {{- with $.Values.labels }}
  labels:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- $crdAnnotations := get $metadata "annotations" }}
  {{- $annotations :=  merge $crdAnnotations $.Values.annotations }}
  annotations:
    {{- $annotations | toYaml | nindent 4 }}
spec: 
{{ get $manifest "spec" | toYaml | indent 2 }}
{{- end }}
