name: Create a release with CRDs

on:
  push:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ github.token }}
      - name: Create a release based on a tag
        uses: softprops/action-gh-release@v2
        id: create_release
        with: 
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
        files: |
          config/crd/bases/*
