name: Publish a helm chart

on:
  push:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    #permissions:
    #  packages: write
    strategy:
      matrix:
        container:
          - file: ./Dockerfile
            name: gcp-kafka-auth-operator
          - file: ./Dockerfile.proxy
            name: gcp-kafka-auth-proxy
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
      - uses: azure/setup-helm@v4.2.0
      - name: Push Helm chart to OCI compatible registry (Github)
        run: |
          export BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          export SHA="+$(git rev-parse --short HEAD)"
          helm registry login ghcr.io \
            --username ${{ github.actor }} \
            --password ${{ github.token }}
          for chart in $(find charts -maxdepth 1 -mindepth 1 -type d); do
            if [ "${BRANCH}" != "main" ]; then
              yq e -i ".version += env(SHA)" "$chart/Chart.yaml"
            fi
            helm package $chart -d chart-packages;
          done
          charts=$(find chart-packages -maxdepth 1 -mindepth 1 -type f)
          for chart in $charts; do
            helm push $chart oci://ghcr.io/${{ github.repository }}
          done
